name: testing

on:
  push:
    branches:
      - "testing"

  pull_request:
    branches:
      - "master"
jobs:
  ci:
    name: fhfbffbjfbfjg
    uses: ./.github/workflows/node.js-ci.yml

  test:
    needs: ci
    name: continuoues integration
    uses: ./.github/workflows/nodetest.yaml